apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: karasu-erp

resources:
  - ../../base/namespace.yaml
  - ../../base/configmap.yaml
  - ../../base/secrets.yaml
  - ../../base/api-deployment.yaml
  - ../../base/worker-deployment.yaml
  - ../../base/ingress.yaml

images:
  - name: ghcr.io/karasu/erp-api
    newTag: latest

replicas:
  - name: karasu-api
    count: 3
  - name: karasu-worker
    count: 2
