apiVersion: v1
kind: ConfigMap
metadata:
  name: karasu-api-config
  namespace: karasu-erp
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Database__Provider: "SqlServer"
  RateLimiting__PermitLimit: "200"
  RateLimiting__AuthPermitLimit: "20"
  RateLimiting__WindowSeconds: "60"
  Jwt__Issuer: "karasu-erp"
  Jwt__Audience: "karasu-erp-clients"
