apiVersion: v1
kind: Secret
metadata:
  name: karasu-secrets
  namespace: karasu-erp
type: Opaque
stringData:
  db-connection: "REPLACE_WITH_CONNECTION_STRING"
  redis-connection: "REPLACE_WITH_REDIS_CONNECTION"
  jwt-secret: "REPLACE_WITH_JWT_SECRET_MIN_32_CHARS"
